[package]
name = "raytracer"
version = "0.1.0"
authors = ["Merzouk OUMEDDAH Aghylas SAI Juba Saadi SARNI 4IABD"]

[dependencies]
serde = "0.9.7"
serde_derive = "0.9.7"
image = "0.12.3"
rayon = "1.3.1"
indicatif = "0.15.0"
